from . import (
    blueprints,
    blueprintsExtraData,
    buildings,
    gameCode,
    gameObjects,
    ingameData,
    islands,
    pygamePIL,
    research,
    savegameObjects,
    savegames,
    shapeCodes,
    shapeOperations,
    shapeViewer,
    translations,
    utils,
    versions
)